env:
  global:
    TERM=dumb
language: java
jdk:
- openjdk8
- oraclejdk8
install: true
before_script:
- sudo apt update -y || true
- sudo apt -y install python-pip
- sudo pip install httpie
- source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
script:
# maven
- ./mvnw
- java -jar target/*.jar &
- wait_for 8080
- http -a user:user   get :8080/
- http -a user:user   get :8080/api/v1/users
- http -a admin:admin get :8080/api/v1/users
- http -a user:user   get :8080/profiles/admin
- http -a admin:admin get :8080/profiles/admin
- http -a admin:admin get :8080/api/v1/users/ accept:application/stream+json
- http -a admin:admin post :8080/api/v1/users username=ololo
- stop_any 8080
# gradle
- ./gradlew
- java -jar build/libs/*.jar &
- wait_for 8080
- http -a user:user   get :8080/
- http -a user:user   get :8080/api/v1/users
- http -a admin:admin get :8080/api/v1/users
- http -a user:user   get :8080/profiles/admin
- http -a admin:admin get :8080/profiles/admin
- http -a admin:admin get :8080/api/v1/users/ accept:application/stream+json
- http -a admin:admin post :8080/api/v1/users username=ololo
- stop_any 8080
cache:
  directories:
  - $HOME/.m2/
  - $HOME/.gradle/
