= reactive security image:https://travis-ci.org/daggerok/csrf-spring-webflux-mustache.svg?branch=master["Build Status", link="https://travis-ci.org/daggerok/csrf-spring-webflux-mustache"]

NOTE: for some reasons gradle building jar which is not working... (so use maven instead)

This repository is contains example of custom reactive repository user details + standard password encoder usage for project on top of:
spring-boot 2, spring-webflux, spring-security 5, reactive mongodb and mustache template engine

.build
----
./mvnw

open http://127.0.0.1
# user / user
# adin / admin

http get :8080/api/v1/users
# 401: Unauthorized

http --auth user:user get :8080/api/v1/users
# OK

http -a user:user get :8080/api/v1/users accept:'text/html'
# same: 200

http --auth user:user post :8080/api/v1/users username=ololo
# 403: CSRF Token has been associated to this client
----

backlog:

. csrf protection, no op password encoder (done link:../../blob/csrf/src/main/java/daggerok/web/SecurityConfig.java[in csrf branch])
. mongo userDetailService, standart password encoder (done link:../../tree/reactive-repository-user-details/[here])
. use project user authentication principal (done link:../../tree/application-authentication-user/[in that branch])
. fix deprecated password encoder (todo)
. pre-auth method security (todo)
. oauth2, spring-cloud (todo)
. authorization-server, resource-server, jwt... (todo)
